RELAY_VERSION = "0.1.0"
MANIFEST_FILE = "Relay.toml"
VCPKG_MANIFEST_FILE = "vcpkg.json"

CMAKE_FIND_START_MARKER = "# <RELAY_DEPENDENCIES_FIND_START>"
CMAKE_FIND_END_MARKER = "# <RELAY_DEPENDENCIES_FIND_END>"
CMAKE_LINK_START_MARKER = "# <RELAY_DEPENDENCIES_LINK_START>"
CMAKE_LINK_END_MARKER = "# <RELAY_DEPENDENCIES_LINK_END>"
CMAKE_DEPENDENCY_MAPPING = {
    "curl": { 
        "find_package": "find_package(CURL REQUIRED)",
        "target_link": "CURL::libcurl"
    },
}